name: jain_metals
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cloud_firestore: ^1.0.5
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.4
  image_picker: ^0.7.4
  photo_view: ^0.11.1
  carousel_slider: ^3.0.0
  dotted_border: ^2.0.0
  firebase_storage_web: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

